export const SET_USERID = 'SET_USERID'

export const SET_COURIER = 'SET_COURIER'

export const SET_COURIER_QUERY = 'SET_COURIER_QUERY'

export const SET_COURIERDETAIL = 'SET_COURIERDETAIL'

export const SET_COURIERDETAIL_QUERY = 'SET_COURIERDETAIL_QUERY'

export const SET_COURIEREXPRESS = 'SET_COURIEREXPRESS'

export const SET_COURIEREXPRESS_QUERY = 'SET_COURIEREXPRESS_QUERY'

export const SET_INCOME = 'SET_INCOME'

export const SET_INCOME_QUERY = 'SET_INCOME_QUERY'

export const SET_DISPATCH = 'SET_DISPATCH'

export const SET_DISPATCH_QUERY = 'SET_DISPATCH_QUERY'
