export const SET_USERID = 'SET_USERID'

export const SET_COURIER = 'SET_COURIER'

export const SET_COURIER_QUERY = 'SET_COURIER_QUERY'

export const SET_COURIERDETAIL = 'SET_COURIERDETAIL'

export const SET_COURIERDETAIL_QUERY = 'SET_COURIERDETAIL_QUERY'
